import Web3Provider from './context/Web3Provider'
import './globals.css'
import { Roboto_Mono } from 'next/font/google'

const font = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Send me your ether plz',
  description: 'Generated by chads',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Web3Provider>
          {children}
        </Web3Provider>
      </body>
    </html>
  )
}
